### ISSUE TITLE
Two small questions

### ISSUE THREAD

**Issue by qsunyuan** [SiLangWHL/vMF-OP#3]
非常精彩的工作！

我个人有两个疑惑，在于apk的梯度：
 
1 - (p-1) / kappa * apk - apk ** 2

1 - 2 / kappa * ( 1/d - 1/(d-1) ) * apk - apk ** 2

其次，

关于 $\log \frac{Cd(k1)}{Cd(k2)}$ 固定第二个kappa为16。

**Comment by SiLangWHL** [comment]
For $\log \frac{Cd(k1)}{Cd(k2)}$, you may indicate Lines 38 and 39 in utils_multi_K_vMF.py. For bias, decreasing the same value for all classes does not change the output probabilities. I just want to normalize the value of bias, for example, the original bias may be in the range of (1, 2), then we adjust it to (0, 1).

**Comment by SiLangWHL** [comment]
For your first question, $1 - \frac{p-1}{\kappa}  Apk - Apk ^2$ is the gradient of Apk.  Because we have calculated and stored the value of Apk in the Forward function. So we can straightly use Apk to accelerate the Backward function.

**Comment by qsunyuan** [comment]
非常感谢
